export const STORE_MOVIE_SEARCH = "STORE_MOVIE_SEARCH";

export const STORE_SEARCH_HISTORY = "STORE_SEARCH_HISTORY";

export const FETCH_MOVIES_BEGIN = "FETCH_MOVIES_BEGIN";

export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";

export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const CLEAR_MOVIES = "CLEAR_MOVIES";